import "../styles/globals.css";
import type { AppProps } from "next/app";
import { createClient, Provider } from "urql";
import Head from "next/head";

const client = createClient({
  url: "https://rickandmortyapi.com/graphql",
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <html>
      <Head>
        <title>R&M Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Provider value={client}>
        <Component {...pageProps} />
      </Provider>
    </html>
  );
}

export default MyApp;
