import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCharachtersQuery } from "../generated/graphql";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import NextLink from "next/link";

const Home = () => {
  const router = useRouter();

  const [{ data, fetching, error }] = useCharachtersQuery();

  console.log(router.query.url);
  return (
    <div className={styles.container}>
      <Head>
        <title>R&M Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div>
          {data?.characters?.results!.map((c) => (
            <NextLink
              key={c!.id}
              href={"/character/[id]"}
              as={`/character/${c!.id}`}
            >
              <div>{c?.name}</div>
            </NextLink>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
